# Generated by Django 2.2.2 on 2021-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.TextField(max_length=10000000)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
            ],
        ),
    ]
